import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import 'global_config.dart';
import 'content_item.dart';
import 'about_us.dart';

class CommonPage extends StatefulWidget {
  String _title;

  CommonPage(this._title);

  @override
  _CommonPageState createState() => _CommonPageState();
}

class _CommonPageState extends State<CommonPage> {
  var Items;

  void getHttp() async {
    try {
      Response response = await Dio().get(
          "https://github-trending-api.now.sh/repositories",
          queryParameters: {"language": widget._title, "since": "daily"});
      setState(() {
        Items = response.data;
      });
    } catch (e) {
      print(e);
    }
  }

  //抽屉
  Widget _Drawer() {
    return new Drawer(
      child: ListView(
        padding: EdgeInsets.zero,
        children: <Widget>[
          DrawerHeader(
            child:Column(
              children: <Widget>[
                CircleAvatar(
                  child: Text('Git'),
                  radius: 40,
                )
                ,
                Text(
                  '关于GitHub Daily',
                  style:
                  TextStyle(fontSize: 20.0, color: Colors.black54),
                )
              ],
            ),
            decoration: BoxDecoration(
              color: Colors.white70,
            ),
          ),
          ListTile(
            leading: Icon(
              Icons.favorite,
              color: GlobalConfig.selectBottomColor,
            ),
            title: Text('关于我们'),
            onTap: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (context) => new AboutUs()));
            },
          ),
          Divider()
        ],
      ),
    );
  }

  @override
  void initState() {
    getHttp();
    super.initState();
  }

  @override
  void didUpdateWidget(CommonPage oldWidget) {
    Items = null;
    getHttp();
    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('GitHub每日 ${widget._title} 榜单'),
          elevation: 0,
        ),
        drawer: _Drawer(),
        body: Items == null
            ? Center(
                child: CircularProgressIndicator(
                  strokeWidth: 3.0,
                ),
              )
            : ListView.separated(
                itemCount: Items == null ? 0 : Items.length,
                separatorBuilder: (context, index) => Divider(),
                itemBuilder: (BuildContext context, int index) {
                  if (Items == null || Items.length == 0) {
                    return Center(
                      child: Text('暂无数据'),
                    );
                  } else {
                    var item = Autogenerated.fromJson(Items[index]);
                    return ContentItem(item,widget._title);
                  }
                }));
  }
}
