import 'package:flutter/material.dart';
import 'global_config.dart';
import 'package:url_launcher/url_launcher.dart';

class ContentItem extends StatelessWidget {
  Autogenerated item;
  final String title;
  ContentItem(this.item,this.title);

  _launchURL(url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }

  @override
  Widget build(BuildContext context) {
    return InkWell(
        onTap: () {
          _launchURL(item.url);
        },
        child: Container(
          padding: const EdgeInsets.all(10),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Expanded(
                flex: 1,
                child: ClipRRect(
                  child: Image.network(item.builtBy.length > 0
                      ? item.builtBy[0].avatar
                      : 'https://placehold.it/200&text=${title}'),
                  borderRadius: BorderRadius.all(Radius.circular(6.0)),
                ),
              ),
              Expanded(
                flex: 3,
                child: Container(
                  alignment: Alignment.topLeft,
                  padding: const EdgeInsets.only(left: 10.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: <Widget>[
                      Padding(
                        padding: const EdgeInsets.only(bottom: 5.0),
                        child: Text(
                          item.name,
                          style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 18.0,
                              color: GlobalConfig.listFontColor),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.only(bottom: 5.0),
                        child: Text(
                          item.description,
                          maxLines: 4,
                          overflow: TextOverflow.ellipsis,
                          style: TextStyle(
                              color: GlobalConfig.listDescColor,
                              fontSize: 14.0),
                        ),
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Text('Star：${item.stars}',
                              style: TextStyle(color: GlobalConfig.grayColor)),
                          Text(
                            'Fork：${item.forks}',
                            style: TextStyle(color: GlobalConfig.grayColor),
                          )
                        ],
                      )
                    ],
                  ),
                ),
              ),
            ],
          ),
        ));
  }
}
