import 'package:flutter/material.dart';

class GlobalConfig {
  //页面背景颜色
  static ThemeData themeData = new ThemeData.dark();
  static Color bgColor = Color.fromARGB(244, 245, 245, 1);
  static Color selectBottomColor = Colors.white;
  static Color drawFontColor = Colors.white;
  static Color listFontColor = Colors.white;
  static Color listDescColor = Colors.white70;
  static Color grayColor = Colors.grey;
}
class Autogenerated {
  String author;
  String name;
  String avatar;
  String url;
  String description;
  String language;
  String languageColor;
  int stars;
  int forks;
  int currentPeriodStars;
  List<BuiltBy> builtBy;

  Autogenerated(
      {this.author,
        this.name,
        this.avatar,
        this.url,
        this.description,
        this.language,
        this.languageColor,
        this.stars,
        this.forks,
        this.currentPeriodStars,
        this.builtBy});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    author = json['author'];
    name = json['name'];
    avatar = json['avatar'];
    url = json['url'];
    description = json['description'];
    language = json['language'];
    languageColor = json['languageColor'];
    stars = json['stars'];
    forks = json['forks'];
    currentPeriodStars = json['currentPeriodStars'];
    if (json['builtBy'] != null) {
      builtBy = new List<BuiltBy>();
      json['builtBy'].forEach((v) {
        builtBy.add(new BuiltBy.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['author'] = this.author;
    data['name'] = this.name;
    data['avatar'] = this.avatar;
    data['url'] = this.url;
    data['description'] = this.description;
    data['language'] = this.language;
    data['languageColor'] = this.languageColor;
    data['stars'] = this.stars;
    data['forks'] = this.forks;
    data['currentPeriodStars'] = this.currentPeriodStars;
    if (this.builtBy != null) {
      data['builtBy'] = this.builtBy.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class BuiltBy {
  String username;
  String href;
  String avatar;

  BuiltBy({this.username, this.href, this.avatar});

  BuiltBy.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    href = json['href'];
    avatar = json['avatar'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['username'] = this.username;
    data['href'] = this.href;
    data['avatar'] = this.avatar;
    return data;
  }
}

